### ISSUE TITLE
Request for Trained Model/Weights

### ISSUE THREAD

**Issue by animikhaich** [karasawatakumi/REVISITING_MonoDepth#1]
Hi @karasawatakumi, 

I really appreciate the open-source codebase and the implementation. I would love to try out the inference using the pre-trained model and potentially use it for Transfer Learning for different application(s). 

However, I was unable to find out the trained model/weights for your implementation. It would be very helpful if you can share the same. 

Thanks.

**Comment by karasawatakumi** [comment]
Hi @animikhaich, thank you for your comment. 
I don't have the trained models for some reason, but if you need them and can wait, I'll run the training and upload models when I have time.

**Comment by animikhaich** [comment]
Hi @karasawatakumi, Sure, that would be very helpful. Please do add the models when your training is complete. Thanks :)

**Comment by karasawatakumi** [comment]
Hi @animikhaich.
I have trained a ResNet-50 model and uploaded the weight file [here](https://drive.google.com/drive/folders/1tuzbA_7is4RVi1oiQ3p_CZbUAl13Rj4s?usp=sharing). 
Note that the scores are different from the ones in README.

For your reference, the results of this model are as follows:

MAE | MSE | RMSE | ABS_REL | LG10 | DELTA1 | DELTA2 | DELTA3
-- | -- | -- | -- | -- | -- | -- | --
0.3405 | 0.3175 | 0.5635 | 0.1282 | 0.0552 | 0.8384 | 0.9666 | 0.9908

Thank you for your interest and request!

**Comment by animikhaich** [comment]
Hi @karasawatakumi,

Thank you very much for your support. :)
